# Generated by Django 4.1.5 on 2023-01-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
